# Gulford data classification

In [25]:
import pandas as pd
import numpy as np
import string,os,re

In [68]:
#import skipthoughts
import csv
import random

In [26]:
os.chdir("E:/VINOD KUMAR/Project_Guf_new")

In [27]:
%time actual_data=pd.read_csv("Gul_clean_sentences_vesion_2.csv",low_memory=False)
%time test_data=pd.read_csv("Gul_april_clean_sentences_version_2.csv",low_memory=False)

Wall time: 4.01 s
Wall time: 168 ms


In [28]:
print("Actual data no of rows and columns:",actual_data.shape,"\nTest data no of rows and columns  :",test_data.shape)

Actual data no of rows and columns: (86554, 20) 
Test data no of rows and columns  : (3308, 20)


In [29]:
print("Actual data no of rows and columns:",actual_data.info(),"\nTest data no of rows and columns  :",test_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86554 entries, 0 to 86553
Data columns (total 20 columns):
FileID                  86554 non-null int64
clientid                86554 non-null int64
PID                     82817 non-null float64
SUMMARY                 83731 non-null object
DATA                    86554 non-null object
Categories1             86554 non-null object
Sub_categories1         86554 non-null object
Categories2             1 non-null object
Sub_categories2         0 non-null float64
Categories3             0 non-null float64
Sub_categories3         0 non-null float64
Categories4             0 non-null float64
Sub_categories4         0 non-null float64
Categories5             0 non-null float64
Sub_categories5         0 non-null float64
Previous_Appointment    86554 non-null object
extracted_sent1         86554 non-null object
extracted_sent2         86554 non-null object
summary                 83727 non-null object
extracted_sent3         86540 non-null obje

In [35]:
#Combining summary column with extracted_sentence3 column in to new column
actual_data['SUMMARY_extracted_sent3'] = actual_data['summary'].map(str) +" " +actual_data['extracted_sent3']
#Combining SUMMARY column with extracted test_sentence column to new column
test_data['SUMMARY_extracted_sent3'] = test_data['summary'].map(str) +" " +test_data['extracted_test_sent3']

In [36]:
#Combining summary column with extracted_sentence3 column in to new column
actual_data['SUMMARY_extracted_sent1'] = actual_data['SUMMARY'].map(str) +" " +actual_data['extracted_sent1']
#Combining SUMMARY column with extracted test_sentence column to new column
test_data['SUMMARY_extracted_sent1'] = test_data['SUMMARY'].map(str) +" " +test_data['extracted_test_sent1']

In [37]:
print("No of missing values actual_data:",sum(actual_data['SUMMARY_extracted_sent3'].isnull()))
print("No of missing values test_data:",sum(test_data['SUMMARY_extracted_sent3'].isnull()))

No of missing values actual_data: 14
No of missing values test_data: 10


In [38]:
actual_data['SUMMARY_extracted_sent3'] = actual_data['SUMMARY_extracted_sent3'].astype(str)
test_data['SUMMARY_extracted_sent3'] = test_data['SUMMARY_extracted_sent3'].astype(str)

In [39]:
actual_data['SUMMARY_extracted_sent1'] = actual_data['SUMMARY_extracted_sent1'].astype(str)
test_data['SUMMARY_extracted_sent1'] = test_data['SUMMARY_extracted_sent1'].astype(str)

In [40]:
#clean the sentence
def clean_str2(string):
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"\'s", " \'s", string)
    string = re.sub(r"\'ve", " \'ve", string)
    string = re.sub(r"n\'t", " n\'t", string)
    string = re.sub(r"\'re", " \'re", string)
    string = re.sub(r"\'d", " \'d", string)
    string = re.sub(r"\'ll", " \'ll", string)
    string = re.sub(r",", " , ", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", " \( ", string)
    string = re.sub(r"\)", " \) ", string)
    string = re.sub(r"\?", " \? ", string)
    string = re.sub(r"\s{2,}", " ", string)
    string = re.sub(r"Phone Note ", " ", string)
    string = re.sub(r"Summary of Call ", " ", string)
    string = re.sub(r"New Medications", " ", string)
    string = re.sub(r"New Allergies ", " ", string)
    string = re.sub(r"Call from Patient ", " ", string)
    string = re.sub(r"Clinical Followup Details ", " ", string)
    string = re.sub(r"Caller ", " ", string)
    string = re.sub(r"Initial call taken by ", " ", string)
    string = re.sub(r"Followup Details ", " ", string)
    string = re.sub(r"Follow-up by ", " ", string)
    string = re.sub(r"Call back at ", " ", string)
    string = re.sub(r"Call from Other Clinic ", " ", string)
    string = re.sub(r"Home Phone ", " ", string)
    string = re.sub(r"Converted from flag ", " ", string)
    string = re.sub(r"Call from Pharmacy ", " ", string)
    string = re.sub(r"Prescriptions ", " ", string)
    string = re.sub(r"Entered by ", " ", string)
    string = re.sub(r"Authorized by ", " ", string)
    string = re.sub(r"Electronically signed by", " ", string)
    string = re.sub(r"Method used ", " ", string)
    string = re.sub(r"Ph ", " ", string)
    string = re.sub(r"Fax ", " ", string)
    string = re.sub(r"RxID ", " ", string)
    string = re.sub(r"Work Phone ", " ", string)
    string = re.sub(r"New Orders wrote", " ", string)
    string = re.sub(r"wrote", " ", string)
    string = re.sub(r"Action Taken ", " ", string)
    string = re.sub(r"To Whom It May Concern ", " ", string)
    string = re.sub(r"Follow up for Phone Call ", " ", string)
    string = re.sub(r"Phone Call Completed ", " ", string)
    string = re.sub(r"Follow up by", " ", string)
    string = re.sub(r"Other Incoming Call "," ", string)
    review_text = string.strip()
    letters_only = re.sub("[^a-zA-Z]", " ", review_text)
    letters_only.lower
    return letters_only

In [41]:
import time
start = time.time()
extracted_sent4=[]
length_data=len(actual_data)
for i in range (0,length_data):
    if i%10000 == 0:
        print ("no.of rows reviews processed:",i)
    extracted_sent4.append(clean_str2(actual_data["SUMMARY_extracted_sent3"][i]))
print("Training took {:0.3f} seconds".format(time.time()-start))

no.of rows reviews processed: 0
no.of rows reviews processed: 10000
no.of rows reviews processed: 20000
no.of rows reviews processed: 30000
no.of rows reviews processed: 40000
no.of rows reviews processed: 50000
no.of rows reviews processed: 60000
no.of rows reviews processed: 70000
no.of rows reviews processed: 80000
Training took 8.769 seconds


In [42]:
import time
start = time.time()
extracted_test_sent4=[]
length_data=len(test_data)
for i in range (0,length_data):
    if i%10000 == 0:
        print ("no.of rows reviews processed:",i)
    extracted_test_sent4.append(clean_str2(test_data["SUMMARY_extracted_sent3"][i]))
print("Training took {:0.3f} seconds".format(time.time()-start))

no.of rows reviews processed: 0
Training took 0.362 seconds


In [43]:
actual_data["SUMMARY_extracted_sent3"]=pd.DataFrame(extracted_sent4)
test_data["SUMMARY_extracted_sent3"]=pd.DataFrame(extracted_test_sent4)

In [44]:
#Converting datatype to str
actual_data['SUMMARY_extracted_sent3'] = actual_data['SUMMARY_extracted_sent3'].astype(str)
test_data['SUMMARY_extracted_sent3'] = test_data['SUMMARY_extracted_sent3'].astype(str)

In [46]:
actual_data['SUMMARY_extracted_sent3'] = actual_data['SUMMARY_extracted_sent3'].apply(lambda x: " ".join(x.lower() for x in x.split()))
test_data['SUMMARY_extracted_sent3'] = test_data['SUMMARY_extracted_sent3'].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [47]:
actual_data['SUMMARY_extracted_sent1'] = actual_data['SUMMARY_extracted_sent1'].astype(str)
test_data['SUMMARY_extracted_sent1'] = test_data['SUMMARY_extracted_sent1'].astype(str)

In [48]:
actual_data['SUMMARY_extracted_sent1'] = actual_data['SUMMARY_extracted_sent1'].apply(lambda x: " ".join(x.lower() for x in x.split()))
test_data['SUMMARY_extracted_sent1'] = test_data['SUMMARY_extracted_sent1'].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [49]:
#Removal of Stop Words
from nltk.corpus import stopwords
stop = stopwords.words('english')+["pm",'nan',"am","aa","FYI","january","february","march","april","may","june","july","august","september","october","november","december"]
%time actual_data['SUMMARY_extracted_sent3'] = actual_data['SUMMARY_extracted_sent3'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
%time test_data['SUMMARY_extracted_sent3']=test_data['SUMMARY_extracted_sent3'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

Wall time: 9.32 s
Wall time: 418 ms


In [50]:
from nltk.corpus import stopwords
stop = stopwords.words('english')+["pm",'nan',"am","aa","FYI","january","february","march","april","may","june","july","august","september","october","november","december"]
actual_data['SUMMARY_extracted_sent1'] = actual_data['SUMMARY_extracted_sent1'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
test_data['SUMMARY_extracted_sent1'] = test_data['SUMMARY_extracted_sent1'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [29]:
#Each word frequency count in Whole Corpus
freq_count_data = pd.Series(' '.join(actual_data['SUMMARY_extracted_sent3']).split()).value_counts()
len(freq_count_data)

39356

In [38]:
# Stemming refers to the removal of suffices, like “ing”, “ly”, “s”, etc. by a simple rule-based approach. 
# For this purpose, we will use PorterStemmer from the NLTK library.
from nltk.stem import PorterStemmer,SnowballStemmer
st = SnowballStemmer('english')
#st = PorterStemmer("english")
actual_data['SnowballStemmer_data'] = actual_data['SUMMARY_extracted_sent3'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))
test_data['SnowballStemmer_data'] = test_data['SUMMARY_extracted_sent3'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

In [11]:
from nltk.stem import PorterStemmer,SnowballStemmer
st = SnowballStemmer('english')
#st = PorterStemmer("english")
actual_data['SnowballStemmer_data1'] = actual_data['SUMMARY_extracted_sent1'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))
test_data['SnowballStemmer_data1'] = test_data['SUMMARY_extracted_sent1'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

In [39]:
freq_count_words_SnowballStemmer= pd.Series(' '.join(actual_data['SnowballStemmer_data']).split()).value_counts()
print(len(freq_count_words_SnowballStemmer))

30823


In [51]:
actual_data.Categories1.value_counts()

ASK_A_DOCTOR     31337
PRESCRIPTION     21490
APPOINTMENTS     19477
MISCELLANEOUS    10848
LAB               3402
Name: Categories1, dtype: int64

In [55]:
#I do aspire here to have balanced classes
num_of_categories = 15000
shuffled = actual_data.reindex(np.random.permutation(actual_data.index))
ASK_A_DOCTOR = shuffled[shuffled['Categories1'] == 'ASK_A_DOCTOR'][:num_of_categories]
PRESCRIPTION = shuffled[shuffled['Categories1'] == 'PRESCRIPTION'][:num_of_categories]
APPOINTMENTS = shuffled[shuffled['Categories1'] == 'APPOINTMENTS'][:num_of_categories]
MISCELLANEOUS = shuffled[shuffled['Categories1'] == 'MISCELLANEOUS'][:num_of_categories]
LAB = shuffled[shuffled['Categories1'] == 'LAB'][:num_of_categories]
concated = pd.concat([ASK_A_DOCTOR,PRESCRIPTION,APPOINTMENTS,MISCELLANEOUS,LAB], ignore_index=True)
#Shuffle the dataset
concated = concated.reindex(np.random.permutation(concated.index))
concated['LABEL'] = 0

In [57]:
from keras.utils.np_utils import to_categorical
#One-hot encode the lab
concated.loc[concated['Categories1'] == 'ASK_A_DOCTOR', 'LABEL'] = 0
concated.loc[concated['Categories1'] == 'PRESCRIPTION', 'LABEL'] = 1
concated.loc[concated['Categories1'] == 'APPOINTMENTS', 'LABEL'] = 2
concated.loc[concated['Categories1'] == 'MISCELLANEOUS', 'LABEL'] = 3
concated.loc[concated['Categories1'] == 'LAB', 'LABEL'] = 4
print(concated['LABEL'][:10])
labels = to_categorical(concated['LABEL'], num_classes=5)
print(labels[:10])
if 'Categories1' in concated.keys():
    concated.drop(['Categories1'], axis=1)

Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


45834    3
47075    3
34826    2
14015    0
13330    0
27173    1
11112    0
13169    0
14403    0
29326    1
Name: LABEL, dtype: int64
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]]


In [58]:
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from keras.models import Sequential
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping

In [61]:
concated["SUMMARY_extracted_sent3"].head()

45834    back injection referral pt called appt dr supp...
47075    unc info hosp visit feeling better todays bett...
34826    appt needed testicular lump found lump testicl...
14015    pink eye stink eye right eye irritated vision ...
13330    vitamin questions rtc question vit please info...
Name: SUMMARY_extracted_sent3, dtype: object

In [62]:
n_most_common_words = 20000
max_len = 130
tokenizer = Tokenizer(num_words=n_most_common_words, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', lower=True)
tokenizer.fit_on_texts(concated["SUMMARY_extracted_sent3"].values)
sequences = tokenizer.texts_to_sequences(concated["SUMMARY_extracted_sent3"].values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

X = pad_sequences(sequences, maxlen=max_len)

Found 32176 unique tokens.


In [63]:
X_train, X_test, y_train, y_test = train_test_split(X , labels, test_size=0.25, random_state=42)

In [64]:
epochs = 10
emb_dim = 128
batch_size = 256
labels[:2]

array([[ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [65]:
print((X_train.shape, y_train.shape, X_test.shape, y_test.shape))

model = Sequential()
model.add(Embedding(n_most_common_words, emb_dim, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.7))
model.add(LSTM(64, dropout=0.7, recurrent_dropout=0.7))
model.add(Dense(5, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
print(model.summary())
history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size,validation_split=0.2,callbacks=[EarlyStopping(monitor='val_loss',patience=7, min_delta=0.0001)])

((44437, 130), (44437, 5), (14813, 130), (14813, 5))
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 130, 128)          2560000   
_________________________________________________________________
spatial_dropout1d_1 (Spatial (None, 130, 128)          0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                49408     
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 325       
Total params: 2,609,733
Trainable params: 2,609,733
Non-trainable params: 0
_________________________________________________________________
None
Train on 35549 samples, validate on 8888 samples
Epoch 1/10
 1280/35549 [>.............................] - ETA: 68814s - loss: 1.6052 - acc: 0.2391

SystemError: <class 'range'> returned a result with an error set
Apply node that caused the error: Elemwise{Composite{(i0 - ((i1 * i2) / (i3 + sqrt(clip(i4, i5, i6)))))}}[(0, 0)](embedding_1/embeddings, InplaceDimShuffle{x,x}.0, Elemwise{Composite{((i0 * i1) + (i2 * i3))}}[(0, 1)].0, TensorConstant{(1, 1) of 1e-08}, Elemwise{Composite{((i0 * i1) + (i2 * sqr(i3)))}}[(0, 1)].0, TensorConstant{(1, 1) of 0.0}, TensorConstant{(1, 1) of inf})
Toposort index: 305
Inputs types: [TensorType(float32, matrix), TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, (True, True)), TensorType(float32, (True, True))]
Inputs shapes: [(20000, 128), (1, 1), (20000, 128), (1, 1), (20000, 128), (1, 1), (1, 1)]
Inputs strides: [(512, 4), (4, 4), (512, 4), (4, 4), (512, 4), (4, 4), (4, 4)]
Inputs values: ['not shown', array([[ 0.00016511]], dtype=float32), 'not shown', array([[  9.99999994e-09]], dtype=float32), 'not shown', array([[ 0.]], dtype=float32), array([[ inf]], dtype=float32)]
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

In [ ]:
accr = model.evaluate(X_test,y_test)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn import cross_validation,linear_model
from sklearn.svm import LinearSVC

C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [13]:
#train and test split
train_x, valid_x, train_y, valid_y = cross_validation.train_test_split(actual_data['SnowballStemmer_data1'], actual_data['Categories1'])

In [81]:
train_x_v1, valid_x_v1, train_y_v1, valid_y_v1 = cross_validation.train_test_split(actual_data['SUMMARY_extracted_sent3'], actual_data['Categories1'])

In [42]:
train_2x, valid_2x, train_2y, valid_2y = cross_validation.train_test_split(actual_data['SnowballStemmer_data'], actual_data['Sub_categories1'])

In [15]:
test_x=test_data["SnowballStemmer_data1"]
#test_x_v1=test_data["SUMMARY_extracted_sent3"]

test_y=test_data["Categories1"]
test_2y=test_data["Sub_categories1"]



# Categories

In [18]:
# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(1,2), max_features=100000)
tfidf_vect_ngram.fit(train_x)
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x)
xvalid_tfidf_ngram =  tfidf_vect_ngram.transform(valid_x)
xtest_tfidf_ngram = tfidf_vect_ngram.transform(test_x)

In [17]:
ch2_train= []
ch2_valid = []
ch2_test = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest = ch1.fit_transform(xtrain_tfidf_ngram,train_y)
    x_validation_chi1_kbest = ch1.transform(xvalid_tfidf_ngram)
    x_test_chi1_kbest = ch1.transform(xtest_tfidf_ngram)
    
    
    clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
   
    clf.fit(x_train_chi1_kbest, train_y)
    
    score_train = clf.score(x_train_chi1_kbest, train_y)
    score_valid = clf.score(x_validation_chi1_kbest, valid_y)
    score_test = clf.score(x_test_chi1_kbest, test_y)
    
    
    ch2_train.append(score_train)
    ch2_valid.append(score_valid)
    ch2_test.append(score_test)
    
%time   

KeyboardInterrupt: 

In [ ]:
%time print ("\ntrain_results:",ch2_train,"\nvalid_results:",ch2_valid,"\ntest_results:",ch2_test)

# Input data without stemming 

In [ ]:
# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(1,2), max_features=100000)
tfidf_vect_ngram.fit(train_x_v1)
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x_v1)
xvalid_tfidf_ngram =  tfidf_vect_ngram.transform(valid_x_v1)
xtest_tfidf_ngram = tfidf_vect_ngram.transform(test_x_v1)

In [86]:
ch2_train= []
ch2_valid = []
ch2_test = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest = ch1.fit_transform(xtrain_tfidf_ngram,train_y_v1)
    x_validation_chi1_kbest = ch1.transform(xvalid_tfidf_ngram)
    x_test_chi1_kbest = ch1.transform(xtest_tfidf_ngram)
    
    
    clf = LinearSVC(C=1.0, max_iter=3000,dual=False)
   
    clf.fit(x_train_chi1_kbest, train_y_v1)
    
    score_train = clf.score(x_train_chi1_kbest, train_y_v1)
    score_valid = clf.score(x_validation_chi1_kbest, valid_y_v1)
    score_test = clf.score(x_test_chi1_kbest, test_y)
    
    
    ch2_train.append(score_train)
    ch2_valid.append(score_valid)
    ch2_test.append(score_test)
    print ("chi2 feature selection evaluation calculated for {} features".format(n))  

chi2 feature selection evaluation calculated for 10000 features
chi2 feature selection evaluation calculated for 20000 features
chi2 feature selection evaluation calculated for 30000 features
chi2 feature selection evaluation calculated for 40000 features
chi2 feature selection evaluation calculated for 50000 features
chi2 feature selection evaluation calculated for 60000 features
chi2 feature selection evaluation calculated for 70000 features
chi2 feature selection evaluation calculated for 80000 features
chi2 feature selection evaluation calculated for 90000 features


In [87]:
%time print ("\ntrain_results:",ch2_train,"\nvalid_results:",ch2_valid,"\ntest_results:",ch2_test)


train_results: [0.84658399445428634, 0.88178387121620583, 0.90636986828930144, 0.92520988985596553, 0.93982900716321338, 0.95129014865593464, 0.96044057613802669, 0.9675729800508357, 0.97302626511592083] 
valid_results: [0.78649660335505334, 0.78326170340588752, 0.78113591201072141, 0.78173667914413791, 0.78118212486713801, 0.7806737834465548, 0.7800730163131383, 0.7790563334719719, 0.77850177919497199] 
test_results: [0.77841596130592505, 0.76995163240628783, 0.76723095525997587, 0.76571946795646917, 0.76420798065296247, 0.76753325272067718, 0.76662636033857312, 0.76753325272067718, 0.76571946795646917]
Wall time: 0 ns


# Logistic Regression

In [21]:
ch2_train= []
ch2_valid = []
ch2_test = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest = ch1.fit_transform(xtrain_tfidf_ngram,train_y)
    x_validation_chi1_kbest = ch1.transform(xvalid_tfidf_ngram)
    x_test_chi1_kbest = ch1.transform(xtest_tfidf_ngram)
    
    
    #clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
    #clf =OneVsRestClassifier(RandomForestClassifier())
    #clf = naive_bayes.MultinomialNB()
    clf = linear_model.LogisticRegression()
   
    clf.fit(x_train_chi1_kbest, train_y)
    
    score_train = clf.score(x_train_chi1_kbest, train_y)
    score_valid = clf.score(x_validation_chi1_kbest, valid_y)
    score_test = clf.score(x_test_chi1_kbest, test_y)
    
    
    ch2_train.append(score_train)
    ch2_valid.append(score_valid)
    ch2_test.append(score_test)
    
%time   

Wall time: 0 ns


In [22]:
%time print ("\ntrain_results:",ch2_train,"\nvalid_results:",ch2_valid,"\ntest_results:",ch2_test)


train_results: [0.81455749826696444, 0.82487868751444193, 0.83110221058307021, 0.83516906724177775, 0.83845028113687126, 0.84094585226835095, 0.84339520911961796, 0.84544404220904257, 0.84693830393591618] 
valid_results: [0.7975414760386339, 0.79948241600813341, 0.80091501455704972, 0.80151578169046633, 0.80133093026479962, 0.80170063311613293, 0.80183927168538283, 0.80225518739313273, 0.80211654882388284] 
test_results: [0.75604594921402657, 0.75997581620314392, 0.76118500604594919, 0.75906892382103985, 0.76088270858524787, 0.7614873035066505, 0.75906892382103985, 0.76058041112454655, 0.76088270858524787]
Wall time: 0 ns


In [23]:
ch2_train= []
ch2_valid = []
ch2_test = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest = ch1.fit_transform(xtrain_tfidf_ngram,train_y)
    x_validation_chi1_kbest = ch1.transform(xvalid_tfidf_ngram)
    x_test_chi1_kbest = ch1.transform(xtest_tfidf_ngram)
    
    
    #clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
    #clf =OneVsRestClassifier(RandomForestClassifier())
    #clf = naive_bayes.MultinomialNB()
    clf = linear_model.LogisticRegression(n_jobs=-1,multi_class='ovr',C=1.0,class_weight="balanced",max_iter=1000)
   
    clf.fit(x_train_chi1_kbest, train_y)
    
    score_train = clf.score(x_train_chi1_kbest, train_y)
    score_valid = clf.score(x_validation_chi1_kbest, valid_y)
    score_test = clf.score(x_test_chi1_kbest, test_y)
    
    
    ch2_train.append(score_train)
    ch2_valid.append(score_valid)
    ch2_test.append(score_test)
    print ("chi2 feature selection evaluation calculated for {} features".format(n))

C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1228: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = -1.
  " = {}.".format(self.n_jobs))


chi2 feature selection evaluation calculated for 10000 features
chi2 feature selection evaluation calculated for 20000 features
chi2 feature selection evaluation calculated for 30000 features
chi2 feature selection evaluation calculated for 40000 features
chi2 feature selection evaluation calculated for 50000 features
chi2 feature selection evaluation calculated for 60000 features
chi2 feature selection evaluation calculated for 70000 features
chi2 feature selection evaluation calculated for 80000 features
chi2 feature selection evaluation calculated for 90000 features


In [24]:
%time print ("\ntrain_results:",ch2_train,"\nvalid_results:",ch2_valid,"\ntest_results:",ch2_test)


train_results: [0.81190787953477628, 0.82358468766848958, 0.82990063929754299, 0.8349534006007856, 0.83815759069552487, 0.84062235230686277, 0.84274820919664173, 0.84479704228606645, 0.8463683278132943] 
valid_results: [0.7959702389204677, 0.79772632746430061, 0.797264198900134, 0.79781875317713391, 0.7978649660335505, 0.79823466888488381, 0.79892786173113362, 0.79869679744905031, 0.79911271315680021] 
test_results: [0.77478839177750902, 0.77418379685610639, 0.7726723095525998, 0.77176541717049574, 0.7726723095525998, 0.77388149939540507, 0.7726723095525998, 0.7744860943168077, 0.77357920193470375]
Wall time: 1 ms


In [79]:
ch2_train= []
ch2_valid = []
ch2_test = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest = ch1.fit_transform(xtrain_tfidf_ngram,train_y)
    x_validation_chi1_kbest = ch1.transform(xvalid_tfidf_ngram)
    x_test_chi1_kbest = ch1.transform(xtest_tfidf_ngram)
    
    
    #clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
    #clf =OneVsRestClassifier(RandomForestClassifier())
    #clf = naive_bayes.MultinomialNB()
    #1,0.1,0.01,0.001,0.0001
    clf = linear_model.LogisticRegression(n_jobs=-1,solver='saga',multi_class='ovr',C=0.01,class_weight="balanced",max_iter=3000,warm_start=True)
   
    clf.fit(x_train_chi1_kbest, train_y)
    
    score_train = clf.score(x_train_chi1_kbest, train_y)
    score_valid = clf.score(x_validation_chi1_kbest, valid_y)
    score_test = clf.score(x_test_chi1_kbest, test_y)
    
    
    ch2_train.append(score_train)
    ch2_valid.append(score_valid)
    ch2_test.append(score_test)
    print ("chi2 feature selection evaluation calculated for {} features".format(n))

C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


chi2 feature selection evaluation calculated for 10000 features
chi2 feature selection evaluation calculated for 20000 features
chi2 feature selection evaluation calculated for 30000 features
chi2 feature selection evaluation calculated for 40000 features
chi2 feature selection evaluation calculated for 50000 features
chi2 feature selection evaluation calculated for 60000 features
chi2 feature selection evaluation calculated for 70000 features
chi2 feature selection evaluation calculated for 80000 features
chi2 feature selection evaluation calculated for 90000 features


In [80]:
%time print ("\ntrain_results:",ch2_train,"\nvalid_results:",ch2_valid,"\ntest_results:",ch2_test)


train_results: [0.75762150504505887, 0.75877686205037354, 0.76068705229916045, 0.76185781406454589, 0.75968574289455437, 0.74210891165370096, 0.76187321882461678, 0.76307479011014401, 0.76375259955326191] 
valid_results: [0.75396275243772815, 0.75280743102731185, 0.75488700956606125, 0.75668931096631087, 0.75400896529414485, 0.73654050556864925, 0.75493322242247796, 0.75474837099681136, 0.75585747955081106] 
test_results: [0.74093107617896015, 0.74153567110036278, 0.74153567110036278, 0.7418379685610641, 0.7418379685610641, 0.72672309552599756, 0.74062877871825872, 0.74093107617896015, 0.74244256348246673]
Wall time: 0 ns


In [76]:
# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(1,3), max_features=100000)
tfidf_vect_ngram.fit(train_x)
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x)
xvalid_tfidf_ngram =  tfidf_vect_ngram.transform(valid_x)
xtest_tfidf_ngram = tfidf_vect_ngram.transform(test_x)

In [77]:
ch2_train= []
ch2_valid = []
ch2_test = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest = ch1.fit_transform(xtrain_tfidf_ngram,train_y)
    x_validation_chi1_kbest = ch1.transform(xvalid_tfidf_ngram)
    x_test_chi1_kbest = ch1.transform(xtest_tfidf_ngram)
    
    
    #clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
    #clf =OneVsRestClassifier(RandomForestClassifier())
    #clf = naive_bayes.MultinomialNB()
    clf = linear_model.LogisticRegression(n_jobs=-1,multi_class='ovr',C=1.0,class_weight="balanced",max_iter=3000)
   
    clf.fit(x_train_chi1_kbest, train_y)
    
    score_train = clf.score(x_train_chi1_kbest, train_y)
    score_valid = clf.score(x_validation_chi1_kbest, valid_y)
    score_test = clf.score(x_test_chi1_kbest, test_y)
    
    
    ch2_train.append(score_train)
    ch2_valid.append(score_valid)
    ch2_test.append(score_test)
    print ("chi2 feature selection evaluation calculated for {} features".format(n))

C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1228: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = -1.
  " = {}.".format(self.n_jobs))


chi2 feature selection evaluation calculated for 10000 features
chi2 feature selection evaluation calculated for 20000 features
chi2 feature selection evaluation calculated for 30000 features
chi2 feature selection evaluation calculated for 40000 features
chi2 feature selection evaluation calculated for 50000 features
chi2 feature selection evaluation calculated for 60000 features
chi2 feature selection evaluation calculated for 70000 features
chi2 feature selection evaluation calculated for 80000 features
chi2 feature selection evaluation calculated for 90000 features


In [78]:
%time print ("\ntrain_results:",ch2_train,"\nvalid_results:",ch2_valid,"\ntest_results:",ch2_test)


train_results: [0.80480628514210895, 0.81480397442809827, 0.82230609258260801, 0.82802125856889774, 0.83251944850958948, 0.83633982900716319, 0.83945159054147733, 0.84236309019487021, 0.84479704228606645] 
valid_results: [0.78538749480105363, 0.78718979620130325, 0.78672766763713664, 0.78714358334488654, 0.78686630620638665, 0.78723600905771984, 0.78728222191413655, 0.78700494477563654, 0.78718979620130325] 
test_results: [0.78688029020556227, 0.78536880290205557, 0.78476420798065294, 0.78536880290205557, 0.785671100362757, 0.78718258766626359, 0.785671100362757, 0.78506650544135426, 0.78476420798065294]
Wall time: 0 ns


# Sub_Categories

In [49]:
%time 
# ngram level tf-idf 
tfidf_vect_ngram2 = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(1,2), max_features=100000)
tfidf_vect_ngram2.fit(train_2x)
xtrain_tfidf_ngram2 =  tfidf_vect_ngram2.transform(train_2x)
xvalid_tfidf_ngram2 =  tfidf_vect_ngram2.transform(valid_2x)
xtest_tfidf_ngram2 = tfidf_vect_ngram2.transform(test_x)

Wall time: 0 ns


In [50]:
%time 
ch2_train2 = []
ch2_valid2 = []
ch2_test2 = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest2 = ch1.fit_transform(xtrain_tfidf_ngram2,train_2y)
    x_validation_chi1_kbest2 = ch1.transform(xvalid_tfidf_ngram2)
    x_test_chi1_kbest2 = ch1.transform(xtest_tfidf_ngram2)
    
    
    clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
   
    clf.fit(x_train_chi1_kbest2, train_2y)
    
    score_train2 = clf.score(x_train_chi1_kbest2, train_2y)
    score_valid2 = clf.score(x_validation_chi1_kbest2, valid_2y)
    score_test2 = clf.score(x_test_chi1_kbest2, test_2y)
    
    
    ch2_train2.append(score_train2)
    ch2_valid2.append(score_valid2)
    ch2_test2.append(score_test2)
    
  

Wall time: 0 ns


In [51]:
%time print ("\ntrain_results:",ch2_train2,"\nvalid_results:",ch2_valid2,"\ntest_results:",ch2_test2)


train_results: [0.7775090502965416, 0.80440576138026654, 0.82165909265963177, 0.83555418624354927, 0.84584456597088498, 0.85274589848263116, 0.85742894554417315, 0.85958561195409378, 0.86128013556188865] 
valid_results: [0.72507971717731878, 0.72249179721798606, 0.72041221867923655, 0.72013494154073665, 0.71981145154582005, 0.71897962013032024, 0.71837885299690374, 0.71773187300707053, 0.71745459586857063] 
test_results: [0.6478234582829504, 0.64842805320435304, 0.64691656590084645, 0.6429866989117291, 0.64238210399032647, 0.64177750906892383, 0.64238210399032647, 0.64147521160822252, 0.64177750906892383]
Wall time: 0 ns


# Logistic regresssion 

In [62]:
%time 
# ngram level tf-idf 
tfidf_vect_ngram2 = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(1,2), max_features=100000)
tfidf_vect_ngram2.fit(train_2x)
xtrain_tfidf_ngram2 =  tfidf_vect_ngram2.transform(train_2x)
xvalid_tfidf_ngram2 =  tfidf_vect_ngram2.transform(valid_2x)
xtest_tfidf_ngram2 = tfidf_vect_ngram2.transform(test_x)

Wall time: 0 ns


In [63]:
%time 
ch2_train2 = []
ch2_valid2 = []
ch2_test2 = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest2 = ch1.fit_transform(xtrain_tfidf_ngram2,train_2y)
    x_validation_chi1_kbest2 = ch1.transform(xvalid_tfidf_ngram2)
    x_test_chi1_kbest2 = ch1.transform(xtest_tfidf_ngram2)
    
    
    #clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
    #clf =OneVsRestClassifier(RandomForestClassifier())
    #clf = naive_bayes.MultinomialNB()
    clf = linear_model.LogisticRegression(n_jobs=-1,multi_class='ovr',C=1.0,class_weight="balanced",max_iter=1000)
    
    clf.fit(x_train_chi1_kbest2, train_2y)
    
    score_train2 = clf.score(x_train_chi1_kbest2, train_2y)
    score_valid2 = clf.score(x_validation_chi1_kbest2, valid_2y)
    score_test2 = clf.score(x_test_chi1_kbest2, test_2y)
    
    
    ch2_train2.append(score_train2)
    ch2_valid2.append(score_valid2)
    ch2_test2.append(score_test2)
    

Wall time: 0 ns


C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1228: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = -1.
  " = {}.".format(self.n_jobs))


In [64]:
%time print ("\ntrain_results:",ch2_train2,"\nvalid_results:",ch2_valid2,"\ntest_results:",ch2_test2)


train_results: [0.72651929446198871, 0.74241700685511824, 0.75216821997997385, 0.75885388585072788, 0.76367557575290768, 0.76734190864977281, 0.76986828930139417, 0.77220981283216517, 0.77368866979896789] 
valid_results: [0.69596561763482601, 0.69846111188132542, 0.70026341328157493, 0.70192707611257454, 0.70285133324090765, 0.70349831323074075, 0.70382180322565735, 0.70382180322565735, 0.70359073894357416] 
test_results: [0.65689238210399037, 0.66112454655380892, 0.66112454655380892, 0.65931076178960102, 0.65810157194679564, 0.65991535671100365, 0.65931076178960102, 0.66051995163240629, 0.66142684401451024]
Wall time: 1 ms


In [69]:
%time 
ch2_train2 = []
ch2_valid2 = []
ch2_test2 = []
for n in np.arange(10000,100000,10000):
    ch1 = SelectKBest(chi2, k=n)
    x_train_chi1_kbest2 = ch1.fit_transform(xtrain_tfidf_ngram2,train_2y)
    x_validation_chi1_kbest2 = ch1.transform(xvalid_tfidf_ngram2)
    x_test_chi1_kbest2 = ch1.transform(xtest_tfidf_ngram2)
    
    
    #clf = LinearSVC(C=1.0,penalty='l1', max_iter=3000,dual=False)
    #clf =OneVsRestClassifier(RandomForestClassifier())
    #clf = naive_bayes.MultinomialNB()
    clf = linear_model.LogisticRegression(n_jobs=-1,multi_class='ovr',C=1.0,class_weight="balanced",max_iter=3000,warm_start=True)
    
    clf.fit(x_train_chi1_kbest2, train_2y)
    
    score_train2 = clf.score(x_train_chi1_kbest2, train_2y)
    score_valid2 = clf.score(x_validation_chi1_kbest2, valid_2y)
    score_test2 = clf.score(x_test_chi1_kbest2, test_2y)
    
    
    ch2_train2.append(score_train2)
    ch2_valid2.append(score_valid2)
    ch2_test2.append(score_test2)
    print ("chi2 feature selection evaluation calculated for {} features".format(n))

Wall time: 0 ns


C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1228: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = -1.
  " = {}.".format(self.n_jobs))


chi2 feature selection evaluation calculated for 10000 features
chi2 feature selection evaluation calculated for 20000 features
chi2 feature selection evaluation calculated for 30000 features
chi2 feature selection evaluation calculated for 40000 features
chi2 feature selection evaluation calculated for 50000 features
chi2 feature selection evaluation calculated for 60000 features
chi2 feature selection evaluation calculated for 70000 features
chi2 feature selection evaluation calculated for 80000 features
chi2 feature selection evaluation calculated for 90000 features


In [70]:
%time print ("\ntrain_results:",ch2_train2,"\nvalid_results:",ch2_valid2,"\ntest_results:",ch2_test2)


train_results: [0.72651929446198871, 0.74241700685511824, 0.75216821997997385, 0.75885388585072788, 0.76367557575290768, 0.76734190864977281, 0.76986828930139417, 0.77220981283216517, 0.77368866979896789] 
valid_results: [0.69596561763482601, 0.69846111188132542, 0.70026341328157493, 0.70192707611257454, 0.70285133324090765, 0.70349831323074075, 0.70382180322565735, 0.70382180322565735, 0.70359073894357416] 
test_results: [0.65689238210399037, 0.66112454655380892, 0.66112454655380892, 0.65931076178960102, 0.65810157194679564, 0.65991535671100365, 0.65931076178960102, 0.66051995163240629, 0.66142684401451024]
Wall time: 0 ns


# Deep Learning

In [113]:
from __future__ import print_function

import os
import sys
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.layers import Dense, Input, Flatten, Dropout, Lambda
from keras.layers import Embedding
from keras.models import Model, Sequential
import tensorflow as tf
import pandas as pd
from sklearn.metrics import recall_score

Using Theano backend.
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\1520\AppData\Local\Continuum\anaconda3\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [97]:

# Let us fix up the target as categories to start with
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
# Converting the categories to label
actual_data.Categories1 = le.fit_transform(actual_data.Categories1)
# Converting the subcategories to labels
actual_data.Sub_categories1 = le.fit_transform(actual_data.Sub_categories1)

# Converting the categories to label
test_data.Categories1 = le.fit_transform(test_data.Categories1)
# Converting the subcategories to labels
test_data.Sub_categories1=le.fit_transform(test_data.Sub_categories1)

In [98]:
X = actual_data.SUMMARY_extracted_sent3.as_matrix()
X_test = test_data.SUMMARY_extracted_sent3.as_matrix()

In [102]:
y1 = actual_data.Categories1
y2 = actual_data.Sub_categories1

y1_test = test_data.Categories1
y2_test = test_data.Sub_categories1

In [107]:
X.shape, y1.shape, X_test.shape, y1_test.shape

((86554,), (86554,), (3308,), (3308,))

In [109]:
MAX_SEQUENCE_LENGTH = 100
MAX_NB_WORDS = 30824
EMBEDDING_DIM = 50
VALIDATION_SPLIT = 0.2

In [111]:
X = np.array(X).flatten()
X=X.astype(str)
X.shape

(86554,)

In [114]:
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)

In [115]:
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

labels = to_categorical(np.asarray(y1))
labels2 = to_categorical(np.asarray(y2))
print('Shape of data tensor:', data.shape)
print('Shape of label tensor:', labels.shape)
print('Shape of label tensor:', labels2.shape)

Found 39357 unique tokens.
Shape of data tensor: (86554, 100)
Shape of label tensor: (86554, 5)
Shape of label tensor: (86554, 20)


In [116]:
labels[0]

array([ 0.,  1.,  0.,  0.,  0.])

In [117]:
labels2[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [118]:
# making the train and validation datasets
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]
labels2 = labels2[indices]
num_validation_samples = int(VALIDATION_SPLIT * data.shape[0])

x_train = data[:-num_validation_samples]
y_train = labels[:-num_validation_samples] # This is for categories as target
y_train2 = labels2[:-num_validation_samples] # This is for subcategories as target

x_val = data[-num_validation_samples:]
y_val = labels[-num_validation_samples:] # This is for categories as target
y_val2 = labels2[-num_validation_samples:] # This is for subcategories as target

In [1]:
# Single hidden layer model
model = Sequential()
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length= x_train.shape[1] ))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(5, activation='softmax'))

NameError: name 'Sequential' is not defined

In [ ]:
from keras import callbacks
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
              patience=5, min_lr=0.00001, verbose=1, epsilon=0.001)
early_stop = callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=7, verbose=1, mode='auto')
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

In [ ]:
#model.fit(data, y=y, batch_size=200, epochs=1, verbose=0, validation_split=0.2, shuffle=True)

model.fit(x_train, y_train,
          batch_size=64,
          epochs=1,
          validation_data=(x_val, y_val),
          callbacks=[reduce_lr, early_stop])

Train on 69244 samples, validate on 17310 samples
Epoch 1/1
 3264/69244 [>.............................] - ETA: 1081575s - loss: 1.3565 - acc: 0.4565

In [ ]:
# The above model is clearly overfitting. So lets add some dropout and do batch norm
from keras.layers.normalization import BatchNormalization
from keras.layers import Activation

model = Sequential()
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length= data.shape[1] ))
model.add(Flatten())
model.add(Dropout(0.2))

# hidden Layer 1
model.add(Dense(100))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

# hidden Layer 2
model.add(Dense(50))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Dense(5, activation='softmax'))

In [ ]:
from keras import callbacks
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
              patience=5, min_lr=0.00001, verbose=1, epsilon=0.001)
early_stop = callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=7, verbose=1, mode='auto')
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

In [ ]:
model.fit(x_train, y_train,
          batch_size=64,
          epochs=2,
          validation_data=(x_val, y_val),
          callbacks=[reduce_lr, early_stop])

# USING GLOVE word2vec instead of plain embeddings

In [ ]:
# Lets try glove embeddings instead of plain embeddings

# first, build index mapping words in the embeddings set
# to their embedding vector

print('Indexing word vectors.')

embeddings_index = {}
f = open('glove.6B.50d.txt',encoding="utf8")
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

# second, prepare text samples and their labels
print('Processing text dataset')

In [ ]:
embedding_dimension = 50
word_index = tokenizer.word_index

In [ ]:
embedding_matrix = np.zeros((len(word_index) + 1, embedding_dimension))
for word, i in word_index.items():
    if i >= MAX_NB_WORDS:
        continue
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector[:embedding_dimension]

In [ ]:
embedding_matrix.shape

In [ ]:
data.shape

In [ ]:
embedding_layer = Embedding(embedding_matrix.shape[0],
                            embedding_matrix.shape[1],
                            weights=[embedding_matrix],
                            input_length=data.shape[1])

In [ ]:
model = Sequential()
# num_words is the number of unique words
# Embedding dimension is the dimension of the hidden layer that we choose --> embedding vector ( we can choose this to be 50, or 100 or so)
# input length is the fixed length of the sentence that we feed to this embedding layer network ( https://stats.stackexchange.com/questions/270546/how-does-keras-embedding-layer-work)
# Here we mentioned trainable = false, because we are directly using the weights from embedding matrix from glove. 
model.add(embedding_layer)
#model.add(Lambda(lambda x: tf.reduce_mean(x, axis=1)))
model.add(Flatten())

model.add(Dropout(0.2))

#Hidden layer 1
model.add(Dense(50))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

#Hidden layer 2
model.add(Dense(25))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Dense(5, activation='softmax'))

In [ ]:
from keras import callbacks
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
              patience=5, min_lr=0.00001, verbose=1, epsilon=0.001)
early_stop = callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=7, verbose=1, mode='auto')
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

In [ ]:
model.fit(x_train, y_train,
          batch_size=64,
          epochs=2,
          validation_data=(x_val, y_val),
          callbacks=[reduce_lr, early_stop])

# Using LSTM instead of MLP
Hence forward we will be using plain embeddings instead of glove word2vec as it has not given great performance ( Suspect words like Rx etc., are being omitted from glove vocabulary)

In [ ]:
from keras.layers.recurrent import LSTM

model = Sequential()
# num_words is the number of unique words
# Embedding dimension is the dimension of the hidden layer that we choose --> embedding vector ( we can choose this to be 50, or 100 or so)
# input length is the fixed length of the sentence that we feed to this embedding layer network ( https://stats.stackexchange.com/questions/270546/how-does-keras-embedding-layer-work)
# Here we mentioned trainable = false, because we are directly using the weights from embedding matrix from glove. 
#model.add(embedding_layer)
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length= data.shape[1] ))
#model.add(Lambda(lambda x: tf.reduce_mean(x, axis=1)))
#model.add(Flatten())
model.add(LSTM(256))
model.add(Dense(5, activation='softmax'))

In [ ]:
from keras import callbacks
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
              patience=5, min_lr=0.00001, verbose=1, epsilon=0.001)
early_stop = callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=7, verbose=1, mode='auto')
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

In [ ]:
model.fit(x_train, y_train,
          batch_size=64,
          epochs=1,
          validation_data=(x_val, y_val),
          callbacks=[reduce_lr, early_stop])

# Using a Convolution net

In [ ]:
from keras.layers import Conv1D, GlobalMaxPooling1D

filters = 256
kernel_size = 3
hidden_dims = 100

In [ ]:
model = Sequential()

# model.add(embedding_layer) --> This uses Glove
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length= x_train.shape[1] )) # --> This is plain embeddings

#model.add(Flatten()) # Not reqiured here (its giving an error if used)

model.add(Dropout(0.2))

# we add a Convolution1D, which will learn filters
# word group filters of size filter_length:
model.add(Conv1D(filters,
                 kernel_size,
                 padding='valid',
                 activation='relu',
                 strides=1))
# we use max pooling:
model.add(GlobalMaxPooling1D())

# We add a vanilla hidden layer:
model.add(Dense(hidden_dims))
model.add(Dropout(0.2))
model.add(Activation('relu'))

# We project onto a single unit output layer, and squash it with a sigmoid:
model.add(Dense(5, activation='softmax'))

In [ ]:
from keras import callbacks
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
              patience=5, min_lr=0.00001, verbose=1, epsilon=0.001)
early_stop = callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=7, verbose=1, mode='auto')
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

In [ ]:
model.fit(x_train, y_train,
          batch_size=64,
          epochs=2,
          validation_data=(x_val, y_val),
          callbacks=[reduce_lr, early_stop])

# CNN + LSTM

In [ ]:
from keras.layers.convolutional import MaxPooling1D

model = Sequential()

# model.add(embedding_layer) --> This uses Glove
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length= x_train.shape[1] )) # --> This is plain embeddings

#model.add(Flatten()) # Not reqiured here (its giving an error if used)

model.add(Dropout(0.2))

# we add a Convolution1D, which will learn filters
# word group filters of size filter_length:
model.add(Conv1D(64,
                 kernel_size,
                 padding='same',
                 activation='relu',
                 strides=1))

# we use max pooling:
model.add(MaxPooling1D(pool_size=2))

model.add(LSTM(100))

model.add(Dropout(0.2))

# We project onto a single unit output layer, and squash it with a sigmoid:
model.add(Dense(5, activation='softmax'))

In [ ]:
from keras import callbacks
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
              patience=5, min_lr=0.00001, verbose=1, epsilon=0.001)
early_stop = callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=7, verbose=1, mode='auto')
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

In [ ]:
modelmodel..fitfit((x_trainx_train,,  y_trainy_train,,
                    batch_size=64,
          epochs=2,
          validation_data=(x_val, y_val),
          callbacks=[reduce_lr, early_stop])

# Prediction for the subcategories:
We will use Conv net model as this gave the best results for the classification of categories

In [ ]:
model2 = Sequential()
model2.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length= x_train.shape[1] )) # --> This is plain embeddings

model2.add(Dropout(0.2))

model2.add(Conv1D(filters,
                 kernel_size,
                 padding='valid',
                 activation='relu',
                 strides=1))

# we use max pooling:
model2.add(GlobalMaxPooling1D())

# We add a vanilla hidden layer:
model2.add(Dense(hidden_dims))
model2.add(Dropout(0.2))
model2.add(Activation('relu'))

model2.add(Dense(20, activation='softmax'))

In [ ]:
from keras import callbacks
reduce_lr = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2,
              patience=5, min_lr=0.00001, verbose=1, epsilon=0.001)
early_stop = callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=7, verbose=1, mode='auto')
model2.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['acc'])

In [ ]:
model2.fit(x_train, y_train2,
          batch_size=64,
          epochs=2,
          validation_data=(x_val, y_val2),
          callbacks=[reduce_lr, early_stop])